-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as Total_revenue
from customer_shopping_behavior
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id 
from customer_shopping_behavior
where discount_applied = 'yes' 
and 
purchase_amount > (select round(avg(purchase_amount),2) from customer_shopping_behavior);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as average_review_rating
from customer_shopping_behavior
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping?
select shipping_type, round(avg(purchase_amount),2) as avg_purchase_amt
from customer_shopping_behavior
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more?
-- Compare average spend and total revenue between subscribers and non-subscribers.
with mycte as (
select subscription_status,
round(avg(purchase_amount),2) as avg_spent,
sum(purchase_amount) as Total_revenue,
count(customer_id) as Total_customer
from customer_shopping_behavior
group by subscription_status)
select case when subscription_status = 'yes'
then 'subscribers' else 'non-subscribers' end as subscription_status,
Total_customer,avg_spent,Total_revenue
from mycte;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(sum(case when discount_applied = 'yes' then 1 else 0 end)*100/count(*),2) as per_of_discount_applied
from customer_shopping_behavior
group by item_purchased
order by per_of_discount_applied desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
-- and show the count of each segment?
with mycte as(
select case 
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal' end as customer_segment
from customer_shopping_behavior)
select customer_segment, count(*) as number_of_customers
from mycte
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
with mycte as (
select category,item_purchased, 
count(item_purchased) as total_orders,
row_number() over (partition by category order by count(item_purchased)) as product_ranking
from customer_shopping_behavior
group by item_purchased,category)
select * from mycte
where product_ranking <=3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
with mycte as (
select case 
when subscription_status = 'Yes' then 'subscribers'
else 'non-subscribers' end as subscription_status,
previous_purchases,customer_id
from customer_shopping_behavior
where previous_purchases >=5)
select subscription_status, count(customer_id) as number_of_customers
from mycte
where previous_purchases >5
group by subscription_status;

-- Q10. What is the revenue % contribution of each age group? 
select age_group, sum(purchase_amount) as revenue,
round(sum(purchase_amount)*100/sum(sum(purchase_amount)) over (),2) as rev_pre_contribution
from customer_shopping_behavior
group by age_group
order by rev_pre_contribution desc;

-- Q11.What percentage of the total purchase amount does each item contribute?
SELECT 
item_purchased,
SUM(purchase_amount) AS total_purchase_amount,
ROUND(SUM(purchase_amount) * 100 / SUM(SUM(purchase_amount)) OVER (), 2) AS percentage
FROM 
    customer_shopping_behavior
GROUP BY 
    item_purchased
order by 
	percentage desc
limit 5;